<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<!--<PackageReference Include="SourceCrafter.LiteSpeedLink.Server" Version="$(LiteSpeedLinkVersion)" />
		<PackageReference Include="SourceCrafter.LiteSpeedLink.Client" Version="$(LiteSpeedLinkVersion)" />
		<PackageReference Include="SourceCrafter.LiteSpeedLink.ServerGenerator" Version="$(LiteSpeedLinkVersion)" PrivateAssets="all" />
		<PackageReference Include="SourceCrafter.LiteSpeedLink.ClientGenerator" Version="$(LiteSpeedLinkVersion)" PrivateAssets="all" />-->
		<PackageReference Include="SourceCrafter.DependencyInjection" Version="2.26.282.289" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		<ProjectReference Include="..\..\SourceCrafter.LiteSpeedLink.Server\SourceCrafter.LiteSpeedLink.Server.csproj" />
		<ProjectReference Include="..\..\SourceCrafter.LiteSpeedLink.Client\SourceCrafter.LiteSpeedLink.Client.csproj" />
		<ProjectReference Include="..\..\SourceCrafter.LiteSpeedLink.ServerGenerator\SourceCrafter.LiteSpeedLink.ServerGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		<ProjectReference Include="..\..\SourceCrafter.LiteSpeedLink.ClientGenerator\SourceCrafter.LiteSpeedLink.ClientGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

</Project>
