<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<Configurations>Debug;Release;DEBUG_SG</Configurations>
		<ServerGarbageCollection>false</ServerGarbageCollection>
		<Optimize>true</Optimize>
		<DefineConstants>$(DefineConstants);DISG_META</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
		<PackageReference Include="MemoryPack" Version="1.21.4" />
		<PackageReference Include="Grpc.AspNetCore.Server" Version="2.71.0" />
		<PackageReference Include="Grpc.Net.Client" Version="2.71.0" />
		<PackageReference Include="Google.Protobuf" Version="3.31.1" />
		<PackageReference Include="Grpc.Tools" Version="2.72.0" PrivateAssets="All" />
		<PackageReference Include="SourceCrafter.DependencyInjection" Version="2.26.282.142" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		<PackageReference Include="SourceCrafter.DependencyInjection.Metadata" Version="2.26.282.142" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<Protobuf Include="Comparison\bench.proto" GrpcServices="Both" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\LiteSpeedLink.Abstractions\LiteSpeedLink.Abstractions.csproj" />
		<ProjectReference Include="..\SourceCrafter.LiteSpeedLink.Client\SourceCrafter.LiteSpeedLink.Client.csproj" />
		<ProjectReference Include="..\SourceCrafter.LiteSpeedLink.Server\SourceCrafter.LiteSpeedLink.Server.csproj" />
		<ProjectReference Include="..\SourceCrafter.LiteSpeedLink.ServerGenerator\SourceCrafter.LiteSpeedLink.ServerGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		<ProjectReference Include="..\SourceCrafter.LiteSpeedLink.ClientGenerator\SourceCrafter.LiteSpeedLink.ClientGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

</Project>
