<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<Configurations>Debug;Release;Pack</Configurations>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MemoryPack" Version="1.21.4" />
		<ProjectReference Include="..\LiteSpeedLink.Abstractions\LiteSpeedLink.Abstractions.csproj" />
		<Compile Include="D:\Code\SourceCrafter.DependencyInjection\SharedMemory\SharedMemory\*.cs">
			<Link>SharedMemory\%(RecursiveDir)%(Filename)%(Extension)</Link>
		</Compile>
	</ItemGroup>

</Project>
