<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>latest</LangVersion>
		<Configurations>Debug;Release;Pack;DEBUG_SG</Configurations>
		<DefineConstants>SG_CONTEXT</DefineConstants>
		<IsTrimmable>true</IsTrimmable>
		<TrimMode>full</TrimMode>
		<IsAotCompatible>true</IsAotCompatible>
		<PublishTrimmed>true</PublishTrimmed>
		<OptimizationPreference>Size</OptimizationPreference>
		<DebugType>none</DebugType>
		<StripSymbols>true</StripSymbols>
		<TrimmerRemoveSymbols>true</TrimmerRemoveSymbols>
		<RestoreAdditionalProjectSources>D:\Code\SourceCrafter.DependencyInjection\publish</RestoreAdditionalProjectSources>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BouncyCastle.Cryptography" Version="2.7.0" />
		<PackageReference Include="MemoryPack" Version="1.21.4" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\LiteSpeedLink.Abstractions\LiteSpeedLink.Abstractions.csproj" PrivateAssets="all" />
	</ItemGroup>

</Project>
