<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PublishAot>true</PublishAot>
		<InvariantGlobalization>true</InvariantGlobalization>
		<Configurations>Debug;Release;DEBUG_SG</Configurations>
		<DefineConstants>$(DefineConstants);DISG_META</DefineConstants>
		<AllowUnsafeBlocks>False</AllowUnsafeBlocks>
		<LangVersion>latest</LangVersion>
		<RestoreAdditionalProjectSources>D:\Code\SourceCrafter.DependencyInjection\publish</RestoreAdditionalProjectSources>
	</PropertyGroup>
	<!--<ItemGroup Condition="'$(PublishBuild)' == 'true'">
		<Compile Remove="$(TEMP)\VSGeneratedDocuments\**\*.cs" />
	</ItemGroup>-->
	
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.9" />
		<PackageReference Include="SourceCrafter.DependencyInjection" Version="10.0.1" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		<PackageReference Include="SourceCrafter.DependencyInjection.Metadata" Version="10.0.1" />
		<PackageReference Include="SourceCrafter.DependencyInjection.MsConfiguration" Version="10.0.1" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		<PackageReference Include="SourceCrafter.DependencyInjection.MsConfiguration.Metadata" Version="10.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Application.Contracts\Application.Contracts.csproj" />
		<ProjectReference Include="..\SourceCrafter.LiteSpeedLink.Helpers\SourceCrafter.LiteSpeedLink.Helpers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		<ProjectReference Include="..\SourceCrafter.LiteSpeedLink.Client\SourceCrafter.LiteSpeedLink.Client.csproj" />
		<ProjectReference Include="..\SourceCrafter.LiteSpeedLink.Server\SourceCrafter.LiteSpeedLink.Server.csproj" />
		<Compile Include="..\LiteSpeedLink.Abstractions\Internals\*.cs">
			<Link>SourceCrafter.LiteSpeedLink.Internals\%(RecursiveDir)%(Filename)%(Extension)</Link>
		</Compile>
	</ItemGroup>

</Project>
